### ISSUE TITLE
how to support multi hotword?Thanks

### ISSUE THREAD

**Issue by xjj210130** [MycroftAI/mycroft-precise#103]
If i want to use mycroft-precise to support multi hotword. will i set the label files?

**Comment by el-tocino** [comment]
This is not currently supported.

**Comment by MatthewScholefield** [comment]
Look at #24 for info on this. Like el-tocino mentioned, it's currently not supported, but there's info there for what would have to be done if anyone were interested. Closing, since discussion can continue there. Let me know if you'd to reopen this.

Thanks
