### ISSUE TITLE
facing error while running precise-listen.

### ISSUE THREAD

**Issue by artinegi1607** [MycroftAI/mycroft-precise#104]
I was trying to run precise-listen but getting the below error.

tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_1/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_1/bias)
	 [[{{node dense_1/BiasAdd/ReadVariableOp}}]]

 Any help would be appreciated.

**Comment by diyfr** [comment]
https://github.com/MycroftAI/mycroft-precise/issues/88#issuecomment-541489364

**Comment by artinegi1607** [comment]
Thanks!  It worked for me.
