### ISSUE TITLE
how to convert my own wav files to desired wav files using ffmpeg?

### ISSUE THREAD

**Issue by mgrove6** [MycroftAI/mycroft-precise#108]
Hi,
I am using a data set from online which has recordings for my own wake word. How to convert those files to the desired output wav files using ffmpeg?

**Comment by el-tocino** [comment]
```ffmpeg -i soundfile.wav -f s16le -ac 1 -ar 16000 -acodec pcm_s16le output.wav```

I use sox (faster for large jobs for me):

```sox inputfilename.wav -r 16000 -b 16 -c 1 outputfilename.wav```
