### ISSUE TITLE
bbopt version is incompatible.

### ISSUE THREAD

**Issue by YuminXue** [MycroftAI/mycroft-precise#110]
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (hyperopt 0.1.2 (/home/shellyxue/mycroft-precise/.venv/lib/python3.5/site-packages), Requirement.parse('hyperopt>=0.2.1; python_version >= "3"'), {'bbopt'})

**Comment by rockiram** [comment]
The latest bbopt version requires hyperopt >=0.2.1.

Install bbopt version 1.1.1  which is compatible with hyperopt 0.1.2
