### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by antoninovara** [MycroftAI/mycroft-precise#114]
Hello everyone!

I'm trying to install mycroft-precise.

I have followed the instructions:
git clone https://github.com/mycroftai/mycroft-precise
cd mycroft-precise
./setup.sh

Everything goes fine until the script tries to install pyspark. In this moment I get an error. 
[https://photos.app.goo.gl/KvH1gAebNtYHNs9HA](url)

I have tried to install pyspark alone but I get the same error.

Thank you very much for your help.

Regards
![20191221_125929](https://user-images.githubusercontent.com/15743045/71307741-1126c500-23f3-11ea-9bc6-ae3e356bd2ef.jpg)

**Comment by el-tocino** [comment]
Can you post the text of the error so it's readable?

**Comment by antoninovara** [comment]
Thank you for answering.

My error was this.
https://photos.app.goo.gl/pBFgutsnzcZwBxtC9

I have installed gfortran and now the process passes this point but I keep trying to install mycroft-precise.

I have expanded the virtual memory, I have run the setup.sh with sudo but no results. The process keeps in this point for ever.
https://photos.app.goo.gl/brnLg3WzhP2Nu3AD6

I was able to install scipy alone but I used pip3. I don't know if change pip for pip3 in the setup.sh is a good idea or not.
https://photos.app.goo.gl/T1rNBkVwSwbFjvpx7

Thank you very much again.

Regards

**Comment by antoninovara** [comment]
Finally, I got it to work. Thank you very much

**Comment by gericho** [comment]
may I ask how you got it to work? I'm on a raspberry Pi3 A with 512 mb ram

**Comment by gericho** [comment]
https://www.bitpi.co/2015/02/11/how-to-change-raspberry-pis-swapfile-size-on-rasbian/

increasing the swap to 2048 did the trick!

**Comment by antoninovara** [comment]
sorry for not answering sooner. This is the trick. Good job!
