### ISSUE TITLE
pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by antoninovara** [MycroftAI/mycroft-precise#116]
I have run precise-collect and i get this error:

> pkg_resources.ContextualVersionConflict: (hyperopt 0.1.2 (/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages), Requirement.parse('hyperopt>=0.2.1; python_version >= "3"'), {'bbopt'})

As you can watch on the image, I have installed bbopt version 1.1.1 with one error but everything looks end fine
https://photos.app.goo.gl/5j6L2rMVXEL4MEBg6

When I try again, I get the same error:

> pkg_resources.ContextualVersionConflict: (hyperopt 0.1.2 (/home/pi/mycroft-precise/.venv/lib/python3.7/site-packages), Requirement.parse('hyperopt>=0.2.1; python_version >= "3"'), {'bbopt'})

Thank you

**Comment by Atul-Anand-Jha** [comment]
Hey @antoninovara , I am facing a similar issue. Did you find any solution?

**Comment by antoninovara** [comment]
Hello! @Atul-Anand-Jha Have you solved your problem?

In my case, it was a problem with pip2 and pip3. Try to check this:
`pip2 list`
`pip3 list`

If it is the problem, you can edit .bashrc file and add:
`alias pip=pip3`

I hope this solves your problem.

Regards

**Comment by Atul-Anand-Jha** [comment]
> Hello! @Atul-Anand-Jha Have you solved your problem?
> 
> In my case, it was a problem with pip2 and pip3. Try to check this:
> `pip2 list`
> `pip3 list`
> 
> If it is the problem, you can edit .bashrc file and add:
> `alias pip=pip3`
> 
> I hope this solves your problem.
> 
> Regards

Thanks for the reply. Although, I have already aliased Pip. 
But , still i will recheck on the next installation run.

**Comment by miladmalekzadeh** [comment]
Hi, 
I have similar issue! I think hyperopt==0.1.2 and 0.2.1 and networks==1.11 and 2.2 have mismatch!
You cannot have a correct combination easily. At least I don't know how?
Could somebody help please?
