### ISSUE TITLE
Had to downgrade keras

### ISSUE THREAD

**Issue by fidesachates** [MycroftAI/mycroft-precise#121]
When running precise train, it complained it could not load tf_utils. Google said to downgrade it to keras 2.1.5 and that would work. I think the other option was to upgrade tensorflow to 2.0, but I was less sure about that as there seemed to be more than one tensorflow packages. 

Downgrading keras worked for me.

**Comment by MatthewScholefield** [comment]
We should probably add `keras<=2.1.5` to `setup.py` and then eventually figure out how to upgrade keras/tensorflow.

**Comment by forslund** [comment]
We've locked the keras version in #124. Closing this issue.
