### ISSUE TITLE
 Is there measured data on the precision and recall of 'hey mycroft.pd'?

### ISSUE THREAD

**Issue by MZLover** [MycroftAI/mycroft-precise#125]
Hello.
I'm not sure if I can post this here. If it's a bad post, we'll move it to the right place

As the title says, are there precision or recall values ​​measured while training the 'hey mycroft' model? Or is there information about other values ​​that can be derived?

I would like to create my own general purpose model and compare it with the figures from 'hey mycroft'.
If you have a list of values, it would be very helpful to share them.

**Comment by MatthewScholefield** [comment]
Precision and recall can be derived from the metrics reported with the `precise-test` command line tool since this reports the number of false positives and false negatives. If you think it'd be a good addition, feel free to submit a PR adding precision and recall to that `precise-test` script.

**Comment by MZLover** [comment]
> Precision and recall can be derived from the metrics reported with the `precise-test` command line tool since this reports the number of false positives and false negatives. If you think it'd be a good addition, feel free to submit a PR adding precision and recall to that `precise-test` script.

understand. But I want to know the values ​​from the dataset that trained the 'hey mycroft' model. This is because I think you will use more and more precisely to train the model than I can prepare...

**Comment by MatthewScholefield** [comment]
Ahh, sorry, I read too quickly. I don't have the value off the top of my head, but false positives were around 5% and false negatives around 10%, but this was based off an untrained portion of the dataset. Since the dataset only captures a biased view of the audio coming into the microphone, it can't necessarily be directly comparable with much else.

**Comment by MZLover** [comment]
> Ahh, sorry, I read too quickly. I don't have the value off the top of my head, but false positives were around 5% and false negatives around 10%, but this was based off an untrained portion of the dataset. Since the dataset only captures a biased view of the audio coming into the microphone, it can't necessarily be directly comparable with much else.


It was the answer I wanted. Thank you.
