### ISSUE TITLE
custom precise wake model issue: warning failed to load params in precise-runner and picroft but works excellent with precise-listen

### ISSUE THREAD

**Issue by michauPe** [MycroftAI/mycroft-precise#127]
I have trained my model 2 weeks ago on ubuntu 18.04 with source install of precise with tensorflow==1.13.1. I have converted it to pb files and tested with precise-listen - it has been working with great accuracy. Problems have occurred with picroft on rpi3b+/4 
- it works with "hey mycroft", "computer", etc but i cant set it up to start detecting my custom wake word
- i have tried all configurations in user config with zero effects
- finally i saw in logs Warning: Failed to load params from pb.params ,the same situation is in precise-runner both ubuntu and rpi

Bellow are my user config and pb.params, please help !
- params: 
{"window_t": 0.1, "hop_t": 0.05, "buffer_t": 1.5, "sample_rate": 16000, "sample_depth": 2, "n_mfcc": 13, "n_filt": 20, "n_fft": 512, "use_delta": false, "vectorizer": 2, "threshold_config": [[6, 4]], "threshold_center": 0.2}
- config:
{
  "max_allowed_core_version": 19.8,

  "listener": {
    "wake_word": "kittResp"
   #"energy_ratio":3
  },
  "hotwords": {
    "kittResp": {
        "module": "precise",
        "phonemes":"HH EY . K IH T .",
        "lang":"en-us",
        "local_model_file": "/home/pi/.mycroft/precise/kittResp.pb",
        "threshold":1e-20
        #"sensitivity":4,
        #"trigger_level":1
}}}

**Comment by forslund** [comment]
Hi, can you provide the model you're using for us to test?

**Comment by michauPe** [comment]
sure, here is the model for "Hey Kit"- trained with Respeaker Mic Array v 2.0



[kitt.zip](https://github.com/MycroftAI/mycroft-precise/files/4219518/kitt.zip)

**Comment by forslund** [comment]
Ok, I have a theory (I haven't tested it yet though) the param file is generated with precise 0.3.0 and the precise-engine used by mycroft is still at 0.2.0 and likely one or more fields has been changed in the param file since then.

will verify...

**Comment by forslund** [comment]
Indeed, downloading the precise engine from the [releases page](https://github.com/MycroftAI/mycroft-precise/releases) and use that to load the model I don't get the warning

**Comment by michauPe** [comment]
ok big thx ! i will check it too.

- Can I update precise engine and use it in picroft without troubles ?
- Have You tested this model with microphone ?

**Comment by forslund** [comment]
I tested it with my mic in precise-listen and had a bit of trouble activating it.

I'll have to get back to you on how to manually switch the precise-version... for me it started to download the old version when I did a quick try...(I think it may work if the old tar.gz is still there but I need to test)

**Comment by forslund** [comment]
Ok for me it worked (on my desktop) if I replaced the directory `~/.mycroft/precise/precise-engine` with the precise directory from the tarball. (leave the rest of the files in `~/.mycroft/precise/intact)

I used this config
```json
{
    "max_allowed_core_version": 19.8,

    "listener": {
        "wake_word": "kittResp"
    },
    "hotwords": {
        "kittResp": { 
            "module": "precise",
            "local_model_file": "/home/ake/projects/kitt/kittResp.pb"
        }
    }
}
```

However I had to talk really close to the mic for it to react.

**Comment by michauPe** [comment]
Oh my god, thx, it's working now! switching version did the job :) maybe itl's good idea to make change in mycroft to include this version on start ?

**Comment by forslund** [comment]
Yes, we should probably update it. I'll add it to my todo.

**Comment by michauPe** [comment]
ok thx
