### ISSUE TITLE
Different prediction when using python

### ISSUE THREAD

**Issue by besimali** [MycroftAI/mycroft-precise#128]
Hi,

I am getting different results in python and command line using the same wav file and same model.

When I feed the wav file from command line as:

`precise-engine mymodel.pb 2048 < wavfile.wav`

I get a list of results by chunks:

```
0.013858976664493464
...
0.7515362837810136
```

I get the same final result if I feed the complete wav file as one chunk. 
However when I try to test the same model an wave file in a python script:

```
  from precise_runner import PreciseEngine, PreciseRunner, ReadWriteStream
 import wave
 
 def activated():
     print("\n\n\nactivated")
 
 def predicted(conf):
     print (conf)
 
 obj = wave.open('wavfile.wav','rb')
 stream = ReadWriteStream()
 
 runner = PreciseRunner(
         PreciseEngine('path/to/precise-engine', 'mymodel.pb'),
     stream=stream, on_activation= activated, on_prediction = predicted)
 runner.start()
 
 data= obj.readframes(2048)
 while len(data) > 0:
     stream.write(data)
     data = obj.readframes(2048)
```

The output is only:

` 0.013858976664493464`

Note that the output is the same as the first chunk result in command line.
I can't find what did I manage to do wrong in this simple script.

**Comment by MatthewScholefield** [comment]
The reason is actually because when feeding via command line there's a wav header that gets interpreted as junk audio. Perhaps `precise-engine` should be modified so that it takes a wave file as a parameter (rather than only from stdin) so that it can skip the header.

**Comment by besimali** [comment]
Thanks Matthew!
However, even with the wav header the result from command line is consistent with what the wav file contatins -  a wake word. Furthermore, I am using the same file that I used for testing the model via precise-test and it was a true positive during testing. 
The problem is that it doesn´t register as a wakeword when using python. And it is interesting that the score is the same as the command line result of 0.013858976664493464 for the first chunk (which I checked to be all zeros).

**Comment by besimali** [comment]
I found out what was the problem.
The main process ended before the engine would consume al the chunks (actually processed only one chunk). This caused the engine to stop as well. A simple `time.sleep(5)` at the end fixed it.
The results are still slightly different than when using `precise-engine` from cmd line, but that is probably because of the wav header that you mentioned.
