### ISSUE TITLE
Installing on Arch Linux (python version)

### ISSUE THREAD

**Issue by DAMO238** [MycroftAI/mycroft-precise#133]
There is no acceptable version of tensorflow for python3.8, so I need to use python3.7. The problem arises when setup.py refuses to use python3.8. I have tried putting python3.7 in the shebang, I have tried putting a `python_requires='==3.7.6'`, I have tried making an alias in zsh. None of these let the setup.py work with the older version. How can I force it to use python3.7?

**Comment by forslund** [comment]
Hi,

I think the main issue is the setup.sh script using

`python3 -m venv "$VENV" --without-pip`

to set up the virtualenvironment for precise, which will use the default system python3 (which is likely 3.8 on your machine if I understood things correctly)

You could try to wipe the .venv folder `rm -rf .venv` and then edit [L51 of setup.sh](https://github.com/MycroftAI/mycroft-precise/blob/dev/setup.sh#L51) changing `python3` to `python3.7`

**Comment by forslund** [comment]
We should allow the setup.sh to take the python executable as an argument

**Comment by DAMO238** [comment]
Thank you, that worked wonders! I also had to change the last 3 lines:

`pip` -> `pip3.7`

**Comment by forslund** [comment]
Glad it worked!
