### ISSUE TITLE
Custom model works great, until put into mycroft.

### ISSUE THREAD

**Issue by DAMO238** [MycroftAI/mycroft-precise#135]
I have trained my custom wake-word, 'Sanjeev'. It works beautifully in precise-test, scoring 98.83% with no false positives and 5.26% (3 out of 203) false negatives. It also works perfectly in precise-listen, activating exactly when it is supposed to. I run precise-convert and put the model into my mycroft-config user file. When I then run mycroft, it cannot recognize me at all...

The keras model, tensorflow model, and a video explaining what I mean can be found at: [https://drive.google.com/drive/folders/1jSYXYjbpiN6cFpTgSMyJ5SLrb8G9obdK?usp=sharing](url)

**Comment by michauPe** [comment]
hello, check this issue https://github.com/MycroftAI/mycroft-precise/issues/127, I had got similar problem

**Comment by DAMO238** [comment]
Thank you, that worked great! For anyone stumbling along this thread, all you need to do is backup your `.mycroft/precise/precise-engine` folder, then get the latest tarball release from their github, and extract it in `.mycroft/precise`. This should make a new folder called precise-engine in their with the engine that should let it work!
