### ISSUE TITLE
KeyError: "The name 'import/net_input' refers to an Operation not in the graph."

### ISSUE THREAD

**Issue by krupalraj** [MycroftAI/mycroft-precise#138]
![image](https://user-images.githubusercontent.com/32962176/77461569-c5881b00-6e28-11ea-89e5-afb389c11181.png)

**Comment by krupalraj** [comment]
i have converted  .net model to .pb using presice-convert
when iam loading the converted model iam getting this error.

**Comment by krupalraj** [comment]
resolved

**Comment by krisgesling** [comment]
Hi @krupalraj glad to hear you got it working. Did you figure out what it was in the end?
