### ISSUE TITLE
the executable：precise-stream is unavailable

### ISSUE THREAD

**Issue by bin872686** [MycroftAI/mycroft-precise#140]

**Comment by forslund** [comment]
Where is it unavailable?

**Comment by forslund** [comment]
Did a quick search, precise-stream is a very old thing that has been removed since v 0.2. Is there some documentation referencing it?

**Comment by forslund** [comment]
Removed the reference I found from the wiki.

**Comment by forslund** [comment]
The reference has been removed and since there's been no more communication here I'm closing the issue.
