### ISSUE TITLE
First start takes up to 10 seconds until precise react to the wake word on RPi

### ISSUE THREAD

**Issue by corus87** [MycroftAI/mycroft-precise#160]
Hi, 
when I say the a wake word right after the start of my [precise example](https://github.com/corus87/precise_example/blob/master/precise_example.py), it doesn’t react to it, it takes almost 10 seconds until there is the activation.
 
After the 10 seconds it react immediately to the wake word. This only happens on the raspberry, on x86 there is no such start delay.
 
Is this a known issue? Or is there maybe something wrong with my example code?

**Comment by MatthewScholefield** [comment]
This is largely the fault of python/tensorflow on raspberry pi. For instance, try running `python3 -c "import tensorflow"`. For me this takes around 8.5 seconds. Add in a few more imports and python's script loading and it probably gets to 10.

This same problem can be seen in `pip3 --version` which takes about 7 seconds on a pi.

**Comment by corus87** [comment]
Oh okay, thank you for clarify this.
