### ISSUE TITLE
Data processing for Tensorflow.js prediction

### ISSUE THREAD

**Issue by ahaight17** [MycroftAI/mycroft-precise#161]
I'm working on a wake word model that I am trying to port to Tensorflow.js. I have followed all the instructions for creating the model and am successfully importing the model to Tensorflow.js. My implementation within Tensorflow.js requires me to understand how the data was formatted when training the model so I can format my audio from the browser the same way. 

I can tell my model has a shape of (null, 29, 13) and #27 indicates that each training sample is 1.5 seconds (potentially front padded with 0s) with 100ms windows and a 50ms hop which gives you 29 segments. I also see [here](https://github.com/MycroftAI/mycroft-precise/blob/dev/precise/params.py#L58) that you are using 13 MFCCs which is where 13 and 29 come from.  I'm also seeing that the sample rate is 16000Hz and a bit depth of 2. 

With all of these values considered, I want to confirm what it would take to get my model to predict outside of Mycroft precise the same way it would using Mycroft precise. My understanding is that I would need to grab 1.5 seconds of audio sampled at 16000Hz, take 100ms of audio data at a time with a sliding window of 50ms for 29 total segments. This means that each segment of audio data would contain (16000*0.1*2) data points (sample rate*length*bit depth). I would take the first 13 MFCCs on each of these 29 segments. Is this the correct approach for processing audio, what else do I need to know in order to process the audio for prediction.

I'm also wondering what that 3-dimensional array looks like for passing to the Mycroft (and Tensorflow) model. Let me know if we can talk deeper about this than answering a few questions on a Github issue.

**Comment by MatthewScholefield** [comment]
What you said sounds correct. You can view an overview of the transformations here: 
https://github.com/MycroftAI/mycroft-precise/wiki/Research#audio-features

You can also see the raw computations in the Sonopy repo here:
https://github.com/MycroftAI/sonopy/blob/master/sonopy.py#L74

Let me know if this helps,
Matthew
