### ISSUE TITLE
cannot find Tensor Flow older versions

### ISSUE THREAD

**Issue by xtr0d3m0n** [MycroftAI/mycroft-precise#175]
When I  try to build from the source pip(pip3) cannot find older tensorflow packages
I know there is a PR for TF2 support but How are you currently building from source?.
can I modify the setup.sh to use pip2?(probably not)
any  solutions? I am on ubuntu 20
```
ERROR: Could not find a version that satisfies the requirement tensorflow<1.14,>=1.13 (from mycroft-precise==0.3.0) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow<1.14,>=1.13 (from mycroft-precise==0.3.0)

```

**Comment by MatthewScholefield** [comment]
You can try installing from source [on the tensorflow 2 fork](https://github.com/MatthewScholefield/mycroft-precise/tree/feature/tf2):
```
git remote add matthew https://github.com/MatthewScholefield/mycroft-precise
git fetch matthew
git checkout feature/tf2

./setup.sh
```

Let me know if this works.

**Comment by xtr0d3m0n** [comment]
@MatthewScholefield Tried this and had to change tensorflow-gpu to cpu from setup.py 
but I get a 
`Illegal instruction (core dumped)`
when I try to run precise-train

**Comment by xtr0d3m0n** [comment]
```
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)

```
found the problem  my cpu dont support the tf version. I am gonna compile from source and I will let you know

**Comment by aalef** [comment]
I'm an Ubuntu 20.04.1 user and applying Matthew's fork my setup.sh after telling
 

>  Running setup.py develop for mycroft-precise

tells

> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
> We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
> h5py 3.0.0 requires numpy>=1.17.5; python_version == "3.8", but you'll have numpy 1.16.0 which is incompatible.
> tensorflow-gpu 2.2.0 requires h5py<2.11.0,>=2.10.0, but you'll have h5py 3.0.0 which is incompatible.

After that, trying to execute a precise-something command aborts with 

> pkg_resources.ContextualVersionConflict: (numpy 1.16.0 (/home/alef/app/mycroft-precise/.venv/lib/python3.8/site-packages), Requirement.parse('numpy>=1.17.5; python_version == "3.8"'), {'h5py'})

Hoping this may help somewhat, my question is: whould precise run in an older environment, such as ubuntu 18 or 19?

**Comment by MatthewScholefield** [comment]
@aalef Try installing what it says inside the venv. So like:
```
source .venv/bin/activate
pip install "numpy>=1.17.6"
pip install ...
```

**Comment by aalef** [comment]
Thanks a lot Mattew, it worked :-)

> @aalef Try installing what it says inside the venv. So like:
> 
> ```
> source .venv/bin/activate
> pip install "numpy>=1.17.6"
> pip install ...
> ```

**Comment by aalef** [comment]
Thanks a lot Mattew, it worked :-)

> @aalef Try installing what it says inside the venv. So like:
> 
> ```
> source .venv/bin/activate
> pip install "numpy>=1.17.6"
> pip install ...

Ehm too early ... module versions are now aligned, but executing

> precise-eval mymodel.net mydata       # already trained under Ubuntu 19.10

ends with

>   File "/mydir/mycroft-precise/.venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
>     for key, item in cls_config.items():
> AttributeError: 'list' object has no attribute 'items'

**EDIT** All is well  @MatthewScholefield. Repeating after having trained a new model works, it was a matter of model format mismatch. Little by little I'm making experience :-)
