### ISSUE TITLE
Train on custom keyword

### ISSUE THREAD

**Issue by dimanshu** [MycroftAI/mycroft-precise#183]
how much data is required to train on a custom keyword?
what should be the length of every keyword .?
can anyone tell me all the steps ?

Data: <TrainData wake_words=3000 not_wake_words=5000 test_wake_words=200 test_not_wake_words=2000>
Loading wake-word...
Loading not-wake-word...
Loading wake-word...
Loading not-wake-word...
Inputs shape: (0, 29, 13)
Outputs shape: (0, 1)
Test inputs shape: (0, 29, 13)
Test outputs shape: (0, 1)
Not enough data to train

**Comment by MatthewScholefield** [comment]
I'm assuming you noticed, but that means it found no data and the file layout might not be correct. I'm just writing this for others to see.

**Comment by dimanshu** [comment]
@MatthewScholefield yes the sample rate was different
