### ISSUE TITLE
The ffmpeg convert command in training tutorial does not work

### ISSUE THREAD

**Issue by EuphoriaCelestial** [MycroftAI/mycroft-precise#186]
Hi, let go straight to the problem, I think this ffmpeg command is wrong:
`$ ffmpeg input.mp3 -acodec pcm_s16le -ar 16000 -ac 1 output.wav`

it should be like this:
`$ ffmpeg -i input.mp3 -acodec pcm_s16le -ar 16000 -ac 1 output.wav`

please change it in the tutorial so other people dont get error when working on it, thanks!

**Comment by krisgesling** [comment]
Thanks for flagging that!
(pun 100% intended)

This has been fixed in the wiki
