### ISSUE TITLE
[Errno 13] Permission Denied (Raspberry Pi 4)

### ISSUE THREAD

**Issue by scuffi** [MycroftAI/mycroft-precise#188]
I have already checked, the entire directory has global read,write,execute permissions. I have also tried running under root permissions yet I still get a permission error:

`PermissionError: [Errno 13] Permission denied: '/home/pi/precise-engine'`

It's from the line:

`engine = PreciseEngine('/home/pi/precise-engine', 'computer-en.pb')`

Not sure if I've missed something obvious here I'm new to this, I've tried running under sudo but it still gives me the same error. 

Sorry if I have missed any key information here. I used the demo code to test before I worked on training my own model but was hit with this.

Python: 3.7.3
Raspberry Pi 4 (Buster)

**Comment by MatthewScholefield** [comment]
The parameter should be an executable file not a folder. I'm assuming you extracted the tar to `/home/pi/precise-engine`. If this is the case, try using `/home/pi/precise-engine/precise-engine` as the parameter.

**Comment by scuffi** [comment]
Thank you! I checked everything except the apparently obvious.

**Comment by MatthewScholefield** [comment]
No problem! I always do the same xD.
