### ISSUE TITLE
Train problem....

### ISSUE THREAD

**Issue by daniele777** [MycroftAI/mycroft-precise#207]
i follow structure of readme and collect wav file …but …i have this error… help !

precise-train -e 60 tars-start.net tars-start/
2021-04-30 19:05:34.881606: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library ‘libcudart.so.11.0’; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-04-30 19:05:34.881702: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
Traceback (most recent call last):
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/bin/precise-train”, line 33, in
sys.exit(load_entry_point(‘mycroft-precise’, ‘console_scripts’, ‘precise-train’)())
File “/home/dani/Scaricati/mycroft-precise-dev/precise/scripts/base_script.py”, line 43, in run_main
script = cls(args)
File “/home/dani/Scaricati/mycroft-precise-dev/precise/scripts/train.py”, line 87, in init
self.model = create_model(args.model, params)
File “/home/dani/Scaricati/mycroft-precise-dev/precise/model.py”, line 76, in create_model
model = Sequential()
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py”, line 522, in _method_wrapper
result = method(self, *args, **kwargs)
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/sequential.py”, line 109, in init
super(functional.Functional, self).init( # pylint: disable=bad-super-call
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py”, line 522, in _method_wrapper
result = method(self, *args, **kwargs)
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/training.py”, line 245, in init
super(Model, self).init(**kwargs)
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py”, line 522, in _method_wrapper
result = method(self, *args, **kwargs)
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/base_layer.py”, line 350, in init
self._init_set_name(name)
File “/home/dani/Scaricati/mycroft-precise-dev/.venv/lib/python3.9/site-packages/keras/engine/functional.py”, line 501, in _init_set_name
self._name = backend.unique_object_name(
AttributeError: module ‘keras.backend’ has no attribute ‘unique_object_name’

**Comment by daniele777** [comment]
No suggestion?? i try to modify keras version ... same problem

**Comment by el-tocino** [comment]
what version of tensorflow? keras? did setup.sh complete without errors?

**Comment by daniele777** [comment]
Hi!! Tensorflow 2.5.0rc1 keras 2.1.5... no problem during installation ...

**Comment by el-tocino** [comment]
Did you download the tf2 fork of precise?

**Comment by daniele777** [comment]
I download and install from main page menù .. so i can't have Nvidia card possibile Is this problem ? I have AMD video card

**Comment by el-tocino** [comment]
It doesn't require a gpu.  

You definitely had problems running setup, or you didn't run it:
  'tensorflow>=1.13,<1.14'

**Comment by daniele777** [comment]
When i try to run pip  install tensorflow==1.13.1  he says : Error no matching distribuition found for tensorflow 1.13.1

**Comment by el-tocino** [comment]
Yeah, you're on python3.9, you'd need to be on 3.7 or less or else compile your own locally.

**Comment by daniele777** [comment]
You are right and can i install python 3.7 and leave 3.9 ? And create venv from python 3.7 ?

**Comment by el-tocino** [comment]
It really depends on your skill and comfort.  Maybe use a different host with older versions?

**Comment by daniele777** [comment]
Yeah best solution i use different host !!!

Thanks Bro !!
