### ISSUE TITLE
Meaning of sample depth

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-precise#22]
From @chidiewenike 
> What does the sample depth represent with regards to preprocessing for the input?

**Comment by MatthewScholefield** [comment]
@chidiewenike Sample depth is the number of bytes each sample takes up. The default settings are to use 16 bit signed integer audio. Since each audio sample is 16 bits, the default sample depth is 2 bytes.

Let me know if this makes sense.

**Comment by chidiewenike** [comment]
Yes, this makes perfect sense. I had a feeling it was bytes. I am just used to seeing audio samples represented in bits. Thank you for the help.
