### ISSUE TITLE
Something seems to be missing

### ISSUE THREAD

**Issue by unstuckconsortium** [MycroftAI/mycroft-precise#240]
I have scoured the Internet and found many suggestions, but it seems to be a deep dark hole that has no way out.  And I'm wondering if it's just me, or have people stopped trying to install mycroft-precise.

It feels like either the source install is missing critical installation files, or the instructions are very light on the installation details.  There is tons of documentation on who to perform the actions to train a new wake word, but when it comes to actually installing the system, key functions appear to be missing.

So following the installation of the source install, which apparently is required to train a new wake word, the git from github works fine.  I even managed to get past the cython install issue.

The place where this gets way out of the understandable universe is when attempting to do the ./setup.sh command.  I can not get past the tensorflow version requirement, no matter how many variations and suggestions I've tried.  

I have built a lubuntu 22.04 VM specifically to perform this function.  I don't want multiple python environments.  I just want to try and train the mycroft wake word.  

I know this sounds frustrated.  And I really do appreciate the effort the Mycroft community is doing around an opensource AI.  And I'd like to help support that too.  But this installation issue I have is just stopping me dead in my tracks.  If I can't get the training software to install, then I don't see how I can proceed with my project.  

All of the guides I've seen so far provide various versions of what libraries and required apps to install to support the training system.  A few have talked about this tensorflow issue.  And short of fully kitting out a phython conda system with the various environments, which didn't work the one time I was brave enough to try, it's just the brick wall that I can't get through.  

I have tried to lower the phython version to 3.7, I've tried installing tensorflow 2.x and 1.13.1, and the wall I hit remains.  

I've tried installing the core as well.  Doesn't help.  

So I have to ask, for those that have tired and succeeded in installing this package,..  is there anyone out there that can tell me what I'm doing wrong that has me this stuck.  

This is the killer error:
ERROR: Could not find a version that satisfies the requirement tensorflow<1.14,>=1.13 (from mycroft-precise) (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0rc0)                                    
ERROR: No matching distribution found for tensorflow<1.14,>=1.13 
After I confirmed I have 1.13.1 installed, I commented out the check for tensorflow in the .py, and I got a ways through before I got a list of errors and missing files and gave me an exit 1 code.  

I'd appreciate any advise or suggestions.  I'm not a Linux noob,..  But I'm not that familiar with python and the virtual environments.

Thanks

**Comment by unstuckconsortium** [comment]
I have persisted and managed to overcome the installation issues.  The main issue seems to be that the precise install is a few years old now, and Linux repositories have progressed.  
So between the instructions listed under the <code> tab, I have also used:
https://community.rhasspy.org/t/mycroft-precise-installation-and-use/628
and
https://github.com/sparky-vision/mycroft-precise-tips/blob/main/README.md

What I finally figured out, was that the setup.sh was looking to install tensorflow 1.13.x.  It had to be newer than 1.13, but older than 1.14 or it wouldn't install.  So I took out the <1.14 part and then tensorflow installed the 2.x versions.

So some important "safety tips" to keep in mind as you go to install.

1) Use something basic like Lubuntu.  I ended up creating a VM of Lubuntu 22.04 on a USB drive with 60 Gb of space.  I first tried an Ubuntu 18.04 I had which got messed up.  I then tried Ubuntu Studio 22.04.  THIS IS BAD!!!!!  The ptaudio19 install will remove a lot of Studio including the Desktop!!!!  Lubuntu doesn't have the same dependencies / requirements.  So less interaction.
2) Install Python 3.7 - Do this first.  
3) Install something like Pyenv.  This will allow you to set an alternative version as your default.  Your default Python environment needs to be 3.7 so when Mycroft-Precise installs, 3.7 is the venv that is installed or you will get mismatch errors
4) Keep in mind that some required modules must be installed in the Python venv (like Cython).  So you may need to wait to install some things until after Precise sets up the venv environment.  Pip is another app that's part of Python that needs to be installed and upgraded.
5) Update the setup.sh to grab tensorflow 1.15.x.  You will still get some depreciation warnings, but it won't fail your training.
6) Don't give up.  It can be done with some persistence.  
7) In the /home/user_name/mycroft-precise/.venv/bin is where you will find the precise-train, precise-listen, etc.  If you make your training audio file directories in there as well, then the instructions work better.  Like : "precise-train -e 150 hey-computer.net hey-computer/"  Where hey-computer/ is the directory.  

Hope this helps someone struggling with the tensorflow like I did.  Enjoy.

**Comment by febreze101** [comment]
Thank you so much for posting this! This is exactly what I needed.
