### ISSUE TITLE
Warning: Failed to load parameters from modelname.params

### ISSUE THREAD

**Issue by bml1g12** [MycroftAI/mycroft-precise#26]
Using Kubuntu v17 and the latest git repo's source. 

I consistently get `Warning: Failed to load parameters from test1.params` when I run things such as `precise-train -e 1 test1 hey-computer/`

Debugging it slightly, I find the error that is being thrown is
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/ben/software/mycroft-precise/.venv/bin/precise-train", line 11, in <module>
    load_entry_point('mycroft-precise', 'console_scripts', 'precise-train')()
  File "/home/ben/software/mycroft-precise/precise/scripts/train.py", line 176, in main
    Trainer().run()
  File "/home/ben/software/mycroft-precise/precise/scripts/train.py", line 80, in __init__
    inject_params(args.model)
  File "/home/ben/software/mycroft-precise/precise/params.py", line 89, in inject_params
    pr.__dict__.update(**compatibility_params, **json.load(f))
TypeError: update() got multiple values for keyword argument 'vectorizer'
```
where compatibility_params ==  ``{'vectorizer': 3}``

and 

test1.params contains `{"window_t": 0.1, "hop_t": 0.05, "buffer_t": 1.5, "sample_rate": 16000, "sample_depth": 2, "n_mfcc": 13, "n_filt": 20, "n_fft": 512, "use_delta": false, "vectorizer": 2}`

**Comment by MatthewScholefield** [comment]
Thanks for reporting this. It was caused by a recent change I made where I didn't realize that the same parameters expanded in a function call wouldn't override each other but rather cause this error. I've changed the line from `.update(**a, **b)` to `.update(a, **b)` so it should now work.

Let me know if you still have any problems with it.

**Comment by bml1g12** [comment]
Thanks, this fixed it.
