### ISSUE TITLE
Is this  support more than on word? thks!

### ISSUE THREAD

**Issue by 858806258** [MycroftAI/mycroft-precise#29]
I want train my own model  with 5 word wake up!

**Comment by MatthewScholefield** [comment]
Unfortunately, not yet. You can only run `precise-engine` multiple times with different models which takes more CPU. To see where we are with supporting multiple wake words via one model, take a look at issue #24. @chidiewenike did get a hacky version working on his machine locally by modifying a lot of the code.

**Comment by xjj210130** [comment]
@MatthewScholefield Do you have a plan to support more than one hot words?thks

**Comment by MatthewScholefield** [comment]
@xjj210130 That's not something currently being worked on. However, it is something we'd love to include if anyone wanted to experimentally implement. #24 has some rough details of how it could be done.
