### ISSUE TITLE
voice recognized or not, can't predicted  

### ISSUE THREAD

**Issue by MuruganR96** [MycroftAI/mycroft-precise#31]
i run on our model with my own audio files,
precise-train -e 60 murugan.net murugan/
precise-convert murugan.net

and finally i tested my audio using this command,
precise-listen murugan.pb

2018-09-12 09:26:53.146783: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX----------------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--------------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx-------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx------

voice recognized or not, i can't predicted. in that instruction what denotes, Demoing the Model (It will listen to the microphone and keep outputting either . if it does not hear the wake word or ! if it does hear it.) but that kind of strategy not applied for this command.

help me sir.  thank you

**Comment by MuruganR96** [comment]
I am not given any not-wake-word samples,
i gave 10 samples for wake-word
i gave 4 samples for test (wake word)
sir i just simply followed for this structure,

hey-computer/
├── wake-word/
│   ├── hey-computer.00.wav
│   ├── hey-computer.01.wav
│   ├── hey-computer.02.wav
│   ├── hey-computer.03.wav
│   ├── hey-computer.04.wav
│   ├── hey-computer.05.wav
│   ├── hey-computer.06.wav
│   ├── hey-computer.07.wav
│   └── hey-computer.08.wav
├── not-wake-word/
└── test/
    ├── wake-word/
    │   ├── hey-computer.09.wav
    │   ├── hey-computer.10.wav
    │   ├── hey-computer.11.wav
    │   └── hey-computer.12.wav
    └── not-wake-word/

sir anyelse i needed or modified in that sample size? thank you sir.

**Comment by MatthewScholefield** [comment]
@MuruganR96 This is expected in this stage of the tutorial. I haven't updated the terminal output (it used to use `!!!` instead of the `XXX` you see), but the key part is:
> As you can see, the model has simply learned to activate to every noise, rather than specifically our wake word. Now what we need to do is reduce false activations by incorporating some data that the model should not activate on. Follow the [reducing false activations](https://github.com/MycroftAI/mycroft-precise/wiki/Training-your-own-wake-word#reducing-false-activations) section to make it actually work.

Let me know if that helps.

**Comment by MatthewScholefield** [comment]
I'm closing this but feel free to reopen if you find a problem.
