### ISSUE TITLE
Binary Install?

### ISSUE THREAD

**Issue by molyswu** [MycroftAI/mycroft-precise#32]
Hi, 
Binary Install 
I try to write my program and run my program :
from precise_runner import PreciseEngine, PreciseRunner

engine = PreciseEngine('/home/yjzx/Downloads/wts/NLP/Picovoice_Porcupine/mycroft-precise/precise-data/precise-engine/precise-engine', 'my_model_file.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))

I can't find  'my_model_file.pb'？

Thank you for your help!

**Comment by MatthewScholefield** [comment]
What do you mean exactly? `my_model_file.pb` is an example string. You can either make your own model and use that file or download an existing one from [here](https://github.com/mycroftai/precise-data/tree/models). For example, you can download the default [hey-mycroft.pb here (extract the tar)](https://github.com/MycroftAI/precise-data/blob/models/hey-mycroft.tar.gz)
