### ISSUE TITLE
How to load  a my_models_file.pb on android system？

### ISSUE THREAD

**Issue by molyswu** [MycroftAI/mycroft-precise#34]
Hi,
 I used precise-train a model file and  precise-convert to   my_models_file.pb.how to load  a my_models_file.pb on android system？

Thank you for your help!

molyswu

**Comment by MatthewScholefield** [comment]
Sorry, right now Precise doesn't support Android. We are open to helping the comunity develop support for it, but not actively working on it. You can track  any progress on issue #5.

Hope this helps!

**Comment by MatthewScholefield** [comment]
I'm closing this since #5 covers the same problem. I'd suggest subscribing to that issue if you'd like updates on it.
