### ISSUE TITLE
How to run model use the binary install option ?

### ISSUE THREAD

**Issue by OrangeBaoWang** [MycroftAI/mycroft-precise#36]
Hi ,when i finished  binary install  on x86_64 , I creat a new py file named test.py. The file content as bellow:
#!/usr/bin/env python3
from precise_runner import PreciseEngine, PreciseRunner
engine = PreciseEngine('precise-engine/precise-engine', 'my_model_file.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))

Finially, I run the test.py ,there is nothing happen. how can i test the model ?

**Comment by MatthewScholefield** [comment]
What model file did you use? Also, could you paste the exact output when you run it? In particular, this script would print "hello" when it hears the wake word.

**Comment by OrangeBaoWang** [comment]
The code in test.py as follows:
  1 #!/usr/bin/env python3
  2 
  3 from precise_runner import PreciseEngine, PreciseRunner
  4 import time
  5 
  6 engine = PreciseEngine('precise-engine/precise-engine', 'hey-mycroft.pb')
  7 runner = PreciseRunner(engine, on_activation=lambda: print('hello'))
  8 
  9 while True:
 10     time.sleep(1)
   When I run test.py,  then,  I speak the word "hey-mycroft", nothing happened as before. Result as follows:
@ubuntu:/mnt/hgfs/project$ python3 test.py

^CTraceback (most recent call last):
  File "test.py", line 10, in <module>
    time.sleep(1)
KeyboardInterrupt
@ubuntu:/mnt/hgfs/project$

**Comment by dnaveenr** [comment]
@OrangeBaoWang , does this work ??
@MatthewScholefield I'm facing the same issue. The program completes execution when you run the sample code.
Please could you provide a working(tested) sample code which works with the binary install. 

Thank you.

**Comment by MatthewScholefield** [comment]
@dnaveenr Here's a working test code:

```python3
#!/usr/bin/env python3
from precise_runner import PreciseEngine, PreciseRunner
import time

engine = PreciseEngine('precise-engine/precise-engine', 'my_model_file.pb')
runner = PreciseRunner(engine, on_activation=lambda: print('hello'))

while True:
    time.sleep(1)
```
Run this with `python3 file.py`. You will need to pay attention to the values `'precise-engine/precise-engine'` and `'my_model_file.pb'` as they will change depending on what model file you are pointing to and where you extracted the binary dir.

**Comment by dnaveenr** [comment]
Thank you. @MatthewScholefield 
Does anything get printed out when we run this ? I do not see any output.

Also, I tried to running https://github.com/MycroftAI/mycroft-precise/blob/dev/runner/example.py . I am using a USB Audio( Respeaker ) with raspberry pi.
I get the following errors:
`ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory`

Any idea to how to solve this ?

**Comment by MatthewScholefield** [comment]
@dnaveenr Those errors are related to ALSA audio (the linux audio system). From what it looks like, the script itself is still running fine. If it heard the wake word it would print `hello`. The problem could be with the audio device not loading properly. More details:

Typically, the `Unknown PCM` errors can be ignored. Those happen in all applications that use ALSA. However, the `Evaluate error:` ones I haven't seen before. There's a chance this is also normal for your audio device, but I'm not sure. Can you verify that your device and microphone setup works properly with other linux python apps (like mycroft-core or a simple audio playback script)?
