### ISSUE TITLE
How to inference(transplant） my model into embedded DSP

### ISSUE THREAD

**Issue by molyswu** [MycroftAI/mycroft-precise#38]
The model I trained wanted to inference  the operation of the DSP chip. My DSP chip is not Linux system, and DSP's programming language supports C. What do we need to do? Do you load model files directly? Do you need to write GRU neural network in C language?
How to inference(transplant） my model into embedded DSP?

Thank you for your help!

**Comment by MatthewScholefield** [comment]
Does your DSP chip support running Tensorflow models via the C++ API?

**Comment by MatthewScholefield** [comment]
No problem. Unfortunately it wouldn't be feasible to support. I would suggest experimenting with either a statistical model or attempting to use a feedforward network via something like [tinn](https://github.com/glouw/tinn).
