### ISSUE TITLE
How the false negatives percentages are calculated ?

### ISSUE THREAD

**Issue by alxistn** [MycroftAI/mycroft-precise#4]
Hello,

I am wondering how the percentages are calculated when I run the follow command:
- precise-test my_model.net dataset/

=== Counts ===
False Positives: 0
True Negatives: 819
False Negatives: 6
True Positives: 43

=== Summary ===
862 out of 868
99.31 %

0.0 % false positives
12.24 % false negatives

**Comment by alxistn** [comment]
Thank you for the precision. I think the labelling is pretty straight forward, I was just a bit confused on how the % were calculated.

Maybe if you write in the read.me or somewhere what you just told me it could help other have a better understanding of what the numbers are.

Thank you for the answer though!

**Comment by MatthewScholefield** [comment]
No problem. I've [added it to the wiki](https://github.com/MycroftAI/mycroft-precise/wiki/How-percentages-are-calculated).
