### ISSUE TITLE
Failed to load parameters from <modelname>.pb.params

### ISSUE THREAD

**Issue by jishminor** [MycroftAI/mycroft-precise#40]
It potentially appears that the binary distribution of the precise engine is out of date with the dev branch here. I am not able to run my custom model, which fails on the message, "Warning: Failed to load parameters from <modelname>.pb.params." The model parameter file contains the key "vectorizer" which seems to not be supported in the params.py file on the master branch. My issue seems related to issue #26

Is the binary distribution up to date with the dev branch?

**Comment by MatthewScholefield** [comment]
No, the binary distribution is up to date with the master branch. What do you think would be the best way to communicate this? (I was thinking we could add this to the readme next to the binary download section)

**Comment by jishminor** [comment]
I think letting everyone know in the readme would be totally fine.

**Comment by jishminor** [comment]
I would also inform everyone on how to build the binary for the dev branch. It was a bit of a hassle for me to do on the raspberry pi.

**Comment by light42** [comment]
> No, the binary distribution is only up to date with the master branch. What do you think would be the best way to communicate this? (I was thinking we could add this to the readme next to the binary download section)

If that's the case, is there a way for me to convert the source install files into executables just like binary install? Because I can only run my wake-word detector with source install.

**Comment by light42** [comment]
> I would also inform everyone on how to build the binary for the dev branch. It was a bit of a hassle for me to do on the raspberry pi.

Forgive my ignorance, but is there any follow-up to this suggestion? Because I still don't see it in docs.

**Comment by MatthewScholefield** [comment]
We should definitely get this documented. I'm seeing if we can make the wiki publicly editable so someone can hopefully contribute, but I can provide some primitive instructions here:
 - Running `./build.sh` will generate two folders in `dist`, `precise-all` containing all executables including training executables, and `precise-engine`, containing only the engine. It will build for your platform. Note: it's probably worth commenting the `package_scripts "precise-all" ...` line in `build.sh` if you just want the engine so that it won't take forever.

**Comment by MatthewScholefield** [comment]
And perhaps we should have a place to share user-build binaries for different platforms so that people only have to do it once

**Comment by light42** [comment]
build.sh points to /usr/lib/python3/dist-packages whenever it tries to build dev binary, which is annoying because the required packages are actually in mycroft-precise environment. How to make it such that it points to mycroft-precise environment packages?

**Comment by light42** [comment]
> We should definitely get this documented. I'm seeing if we can make the wiki publicly editable so someone can hopefully contribute, but I can provide some primitive instructions here:
> 
>     * Running `./build.sh` will generate two folders in `dist`, `precise-all` containing all executables including training executables, and `precise-engine`, containing only the engine. It will build for your platform. Note: it's probably worth commenting the `package_scripts "precise-all" ...` line in `build.sh` if you just want the engine so that it won't take forever.

Reminder for everyone who wants to build dev binaries:

build.sh calls setup.py to get all the dependencies which install numpy 1.13.x which will crashed build.sh, because currently building the dev binary actually requires numpy >= 1.16.0.

**Comment by light42** [comment]
> We should definitely get this documented. I'm seeing if we can make the wiki publicly editable so someone can hopefully contribute, but I can provide some primitive instructions here:
> 
> * Running `./build.sh` will generate two folders in `dist`, `precise-all` containing all executables including training executables, and `precise-engine`, containing only the engine. It will build for your platform. Note: it's probably worth commenting the `package_scripts "precise-all" ...` line in `build.sh` if you just want the engine so that it won't take forever.

I've built it following this method. But the result is the size of the binary becomes ~500mb, two-third of it comes from tensorflow packages. How could I reduce it?
