### ISSUE TITLE
Instructions don't work, possibly missing a step

### ISSUE THREAD

**Issue by JuliaC29** [MycroftAI/mycroft-precise#41]
I downloaded precise and followed the instructions, but I get an error:

```
 1503  git clone https://github.com/mycroftai/mycroft-precise
 1504  ls
 1505  cd mycroft-precise/
 1506  ls
 1507  ./setup.sh
```
Error:
```
juyeon@juyeonubuntu:~/mycroft-precise$ python3 wakeword.py 
Traceback (most recent call last):
  File "wakeword.py", line 3, in <module>
    from precise_runner import PreciseEngine, PreciseRunner
ModuleNotFoundError: No module named 'precise_runner'
```
The setup seemed to complete fine:
https://paste2.org/UIvXhz3I

**Comment by MatthewScholefield** [comment]
@JuliaC29 Make sure to use the Python virtual environment that precise was installed to. To do this, run the command:
```bash
source .venv/bin/activate
```
before using `python` to run the script. I've updated (7d539f34) the README with that detail.

Let me know if this helps.

**Comment by JuliaC29** [comment]
that worked. Thanks @MatthewScholefield
