### ISSUE TITLE
how to convert keras model end with ".net" into  h5?

### ISSUE THREAD

**Issue by shipleyxie** [MycroftAI/mycroft-precise#55]
in Matlab 2018b, there is a function : 
`Layers = importKerasLayers(ModelFile) imports a Keras network
  architecture from ModelFile.
ModelFile       - Name of a Keras model file, specified as a string
                     or a char array. The file must be HDF5 (.h5) or JSON
                     (.json) format.
`
and it only accept .h5 and .json file 
I am confused with your precise.net ,what is the diffrence between .net and .h5?

**Comment by shipleyxie** [comment]
change `.net` to` .h5 `got this error:
`>> Layers=importKerasLayers('test.h5')`
`Error using importKerasLayers (line 104)`
`Reference to non-existent field 'class_name'.`

and i think there some mistake with the saved `precise.net` file.

################################################
`importKerasLayers` in Matalb will import a Keras network architecture from a model file.
`importKerasNetwork` in Matlab will Import a Keras network and weights from a model file.
################################################
if i choose `importKerasNetwork` , modelfile and weights are needed:
```
% load the DNN model which is trained by python.
modelfile = 'model5layers1r001.json'; % load DNN structure
weights = 'model5layers1r001.h5'; % load weights and bias in DNN model
net = importKerasNetwork(modelfile,'WeightFile',weights, ...
      'OutputLayerType','regression');
```
i need another scripts to produce this two file, and i'm trying to solve it.

**Comment by MatthewScholefield** [comment]
Oh, `.net` is a *combined* `.h5` file which stores both the architecture and the weights together. What you want to do is split that file into `.h5` and `.json`. You can manually separate them in keras by doing the following:
```python3
from keras.models import load_model

model = load_model('test.net')
with open("test.json", "w") as f:
    f.write(model.to_json())
model.save_weights("test.h5")
```

Let me know if this works.

**Comment by shipleyxie** [comment]
got this error:
`ValueError: Unknown loss function:weighted_log_loss`
 i'm try to solving...

**Comment by MatthewScholefield** [comment]
Ah, that's an issue with the custom loss function Precise uses. You can solve this by instead using Precise's loader followed by overriding the loss function (make sure to run this inside Precise's virtual environment):
```python
from precise.model import load_precise_model
model = load_precise_model('test.net')
model.compile('rmsprop', 'binary_crossentropy')  # Get rid of Precise's custom loss function

# Same as above:
with open("test.json", "w") as f:
    f.write(model.to_json())
model.save_weights("test.h5")
```
This will override the custom

**Comment by shipleyxie** [comment]
```
from keras.models import load_model

LOSS_BIAS = 0.9
def weighted_log_loss(yt, yp):
    """
    Binary crossentropy with a bias towards false negatives
    yt: Target
    yp: Prediction
    """
    from keras import backend as K

    pos_loss = -(0 + yt) * K.log(0 + yp + K.epsilon())
    neg_loss = -(1 - yt) * K.log(1 - yp + K.epsilon())

    return LOSS_BIAS * K.mean(neg_loss) + (1. - LOSS_BIAS) * K.mean(pos_loss)


model = load_model('test.net',custom_objects={'weighted_log_loss':weighted_log_loss })
with open("test.json", "w") as f:
    f.write(model.to_json())
model.save_weights("test.h5"
```
this code works
and i use it in Matlab, got the same ERROR:
```
>> net = importKerasNetwork('test.json', 'WeightFile','test.h5','OutputLayerType','regression')
Error using importKerasNetwork (line 86)
Reference to non-existent field 'class_name'
```

**Comment by shipleyxie** [comment]
i still confused about this ERROR,
this file contain two file (one succeed(this from another project) ,one failed(this from Precise)), but i don't know why.
[for_test.zip](https://github.com/MycroftAI/mycroft-precise/files/2748523/for_test.zip)
and i'm still try to solve it...

**Comment by shipleyxie** [comment]
The default Version of Keras is 2.2.0 which is not supported by Matlab, change it to 2.1.2, slove this.
