### ISSUE TITLE
Using Runner Examply.py

### ISSUE THREAD

**Issue by george-ai** [MycroftAI/mycroft-precise#56]
Hi there

I have followed the instructions and completed my trained model. 

When running `precise-listen hey-jarvis.net` my wake word is detected with no false positives. This also works for  `precise-listen hey-jarvis.pb`

The below is output from `precise-test hey-jarvis.net hey-jarvis/`

`Loading wake-word...
Loading not-wake-word...
Using TensorFlow backend.
Data: <TrainData wake_words=25 not_wake_words=694 test_wake_words=6 test_not_wake_words=562>
=== False Positives ===

=== False Negatives ===

=== Counts ===
False Positives: 0
True Negatives: 562
False Negatives: 0
True Positives: 6

=== Summary ===
568 out of 568
100.0 %

0.0 % false positives
0.0 % false negatives
`
However when I am using the example.py runner script provided in the repo, the wake word is not working.

I have converted my wake word to .pb. Herewith the command I am using for the example.py file:

`python example.py precise-engine/precise-engine hey-jarvis.pb`

The output when running the above:

`ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Warning: Failed to load parameters from ./hey-jarvis.pb.params
...........................................`

Any help will be greatly appreciated.

Note: I am using the compiled precise engine from https://github.com/MycroftAI/precise-data/blob/dist/x86_64/latest and running Ubunto 18.

**Comment by george-ai** [comment]
All sorted. I am now using the source install engine and not the binary download.

**Comment by MatthewScholefield** [comment]
That's great to hear! I'm closing this for now.
