### ISSUE TITLE
Trained model doesn't trigger

### ISSUE THREAD

**Issue by torntrousers** [MycroftAI/mycroft-precise#58]
I've trained a model with the phrase 'lamp on' following the guide [here](https://github.com/MycroftAI/mycroft-precise/wiki/Training-your-own-wake-word#how-to-train-your-own-wake-word) but then using the result I can't get any triggers when ```running precise-listen``` and saying the phrase 'lamp on'. Could I have done something wrong somewhere? How can I debug this? The generated model is zipped up [here](https://github.com/HarringayMakerSpace/precise-models/blob/master/lamp-on.zip), can you see anything from that?

**Comment by el-tocino** [comment]
in your "test" directory, you should have a "wake-word" as well as "not-wake-word" directories, with each populated by the relevant files. 

You should add a significant amount of not-wake-word data, particularly words/phrases that start similarly, and ones that contain similar phonemes.  (camp on, crampon, lantern, amped up, etc).  A mention over on chat by matthew indicated a 1:5 wake:fake word ratio was their target.  More data in general isn't a bad idea for the whole thing, either.  

When you train, run ```precise-train (options) && precise-test (model)``` to get an idea how it performed on your data.

**Comment by torntrousers** [comment]
Ah yes, having the folders lamp-on/test/wake-word/ does fix it. Thanks!
