### ISSUE TITLE
How to make mycroft-record read stream on stdin

### ISSUE THREAD

**Issue by alxistn** [MycroftAI/mycroft-precise#6]
How can you make mycroft analyse from a stream instead of the mic ?

I would like to do something like:
mycroft-record my_model.net http://my-stream-url/

**Comment by MatthewScholefield** [comment]
If the stream is already a 16000 sample-rate single channel wav, you can do this using the `precise-engine` directly:
```bash
curl http://my-stream-url/ | precise-engine my_model.net 2048
```
Let me know if this works.

**Comment by alxistn** [comment]
Ok it works but not as I expected ahah.

Let me explain what I am trying to do: I have a mic and I stream the audio on a websocket to a local server. On this local server I create a child process with mycroft and the model I trained. I pipe the audio stream to the child process so mycroft can read the audio stream and detect/or not the wake word I trained the model on.

Here, mycroft read the stream, then display the result and stop reading. I would need a way to do what the binary "mycroft-listen" do with the mic, but instead of getting the audio from the mic, it gets it from any stream. 

I'm not sure if I'm clear in my explanations..

**Comment by MatthewScholefield** [comment]
So, for this you'll have to write some Python code. The basis is using Precise's `ReadWriteStream` in between whatever code you use to get the raw bytes and the `PreciseRunner` instance. You can pass this stream object into the constructor. Here's a simple example:
```python
stream = ReadWriteStream()
runner = PreciseRunner(
    PreciseEngine('.venv/bin/precise-engine', 'my-model.pb.or.net'),
    stream=stream, on_activation=lambda: print('Activated!')
)
runner.start()
```
Now you can get your bytes from the stream however you do it and pass them in like this:

```python
while True:
    audio_chunk = read_bytes_from_network()  # Example data: b'\xx\a0\22\26\46\c5\d5\f0'
    stream.write(audio_chunk)
```

If you wanted to use just plain sockets, I just wrote [an implementation of it](https://gist.github.com/MatthewScholefield/e842d9af5a10b5c9e96ea1a07d12e4dc) for fun. You run the server once and you can run the client multiple times on different devices and then it will run precise on each input stream.

**Comment by alxistn** [comment]
Your multi-client / server code is working really well! Thank you.

However when I try your other piece of code and do the following:

`
stream = ReadWriteStream()
runner = PreciseRunner(
    PreciseEngine('.venv/bin/precise-engine', 'power.pb'),
    stream=stream, on_activation=lambda: print('Activated!')
)
runner.start()

while True:
    audio_chunk = sys.stdin.buffer.read(2048) # read_bytes_from_network()  # Example data: b'\xx\a0\22\26\46\c5\d5\f0'
    stream.write(audio_chunk)
`

I keep having this error: 
`
    raise ValueError('Invalid chunk size: ' + str(len(chunk)))
ValueError: Invalid chunk size: 1024
`
I am piping a wav audio file on the stdin of the executable containing the code.

**Comment by MatthewScholefield** [comment]
@alxistn Thanks for pointing that out. It was a bug with how Precise read from a stream. It should be fixed now in the dev branch. Let me know if it works now.

**Comment by alxistn** [comment]
OK so I pulled from the dev branch to be up to date and now this peace of code is working well:

```
    	stream.write(sys.stdin.buffer.read())
    	sock.sendall(stream.read(CHUNK_SIZE))
```

and the precise_server.py is detecting all the activation! 

Thanks a lot for the help I'm grateful!

**Comment by MatthewScholefield** [comment]
Welcome!
