### ISSUE TITLE
source code for precise-engine

### ISSUE THREAD

**Issue by TKNgu** [MycroftAI/mycroft-precise#60]
Hi. Where I can find source code of precise-engine ? I have a android tv box but can run precise-engine binary file (@_@!).
Sorry for my  English.

**Comment by MatthewScholefield** [comment]
Hi, this repository is the source code for precise-engine. You can install it using the [source install](https://github.com/MycroftAI/mycroft-precise#source-install) method. Specifically, `precise-engine` refers to [this script](https://github.com/MycroftAI/mycroft-precise/blob/dev/precise/scripts/engine.py) which is listed as a python console script [here](https://github.com/MycroftAI/mycroft-precise/blob/dev/setup.py#L59).

Let me know if this helps.

**Comment by TKNgu** [comment]
Thank for help. I had find way to run .pb filde model in android.
Sorry for my English.

**Comment by amadrezafrh** [comment]
@TKNgu hi can you help me with using this model on android?
