### ISSUE TITLE
GPU Processing?

### ISSUE THREAD

**Issue by george-ai** [MycroftAI/mycroft-precise#65]
Hi There

Is it possible to use GPU processing in Precise?

**Comment by george-ai** [comment]
Thanks @el-tocino 

That is nice! Thank you for confirming.

**Comment by MatthewScholefield** [comment]
Yep, you should be able to install `tensorflow-gpu` in the venv (or follow all the steps to get Keras/tensorflow working with the GPU) and then it should train by default with it. Feel free to comment if you have any troubles setting it up. For now, I'll close this.
