### ISSUE TITLE
Failed to load parameters from my_model_file.pb.params

### ISSUE THREAD

**Issue by rajdpandey** [MycroftAI/mycroft-precise#69]
Having Error file not found and at the end ValueError: could not convert string to float.
I am trying to run sample provided for binary install. After installation I created file using sample code and tried to run it then it shows above error.

**Comment by MatthewScholefield** [comment]
Sorry about the delayed response. Make sure that you train using the same version that you run with. For example, if you are using the binary install for version `0.2.0` you would want to make sure you train it using the `0.2.0` branch of the code. Additionally, you could try using the recently published binaries for version `0.3.0`.

Let ma know if this helps.

**Comment by rajdpandey** [comment]
No Problem My Problem was Solved with the Help of Chat forum.

**Comment by sujithrkumar** [comment]
please how the problem was solved @rajdpandey

**Comment by JaioSkura** [comment]
Hi! 
I have the same problem... how did you fix it?
