### ISSUE TITLE
Can this program detect a keyword from a sentence or conversation?

### ISSUE THREAD

**Issue by lyuzhilinag** [MycroftAI/mycroft-precise#76]
Can this program detect a keyword from a sentence for conversation audio which contains this keyword or it could just be triggered on hearing a single word? The test input data is a single word or could be a sentence audio file?

**Comment by penrods** [comment]
Yes.  This is designed to continuously analyze an audio steam to find a short pattern.

**Comment by lyuzhilinag** [comment]
> Yes. This is designed to continuously analyze an audio steam to find a short pattern.

thanks a lot
