### ISSUE TITLE
Demoing the Model, No such file or directory: 'play'

### ISSUE THREAD

**Issue by lyuzhilinag** [MycroftAI/mycroft-precise#77]
My OS is MacOS10.13.6, I followed the training instructions and things worked fine until I tried Demoing the Model, I executed 'precise-listen hey-computer.net' in the terminal and got this error, seems the play framework is missing:
`(.venv) LyuzhiliangdeMacBook-Air-2:mycroft-precise lyuzhiliang$ precise-listen hey-computer.net
Using TensorFlow backend.
WARNING:tensorflow:From /Users/lyuzhiliang/mycroft-precise/.venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /Users/lyuzhiliang/mycroft-precise/.venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
XXXXXXXXXXXXXXX-----------------------------------------------------------------
XXXXXXXXXXXXXXXXXXXXXXX---------------------------------------------------------
XXXXXXXXXXXXXXXXXX--------------------------------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX----------------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX------------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx---------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx------------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx-------------------------------
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxx-----------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/lyuzhiliang/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/lyuzhiliang/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lyuzhiliang/mycroft-precise/runner/precise_runner/runner.py", line 239, in _handle_predictions
    self.on_activation()
  File "/Users/lyuzhiliang/mycroft-precise/precise/scripts/listen.py", line 59, in on_activation
    activate_notify()
  File "/Users/lyuzhiliang/mycroft-precise/precise/util.py", line 85, in activate_notify
    play_audio(audio)
  File "/Users/lyuzhiliang/mycroft-precise/precise/util.py", line 78, in play_audio
    Popen([player, '-q', filename])
  File "/Users/lyuzhiliang/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Users/lyuzhiliang/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'play': 'play'`

**Comment by lyuzhilinag** [comment]
Solved with [https://stackoverflow.com/questions/56474678/subprocess-popen-couldnt-find-play](url)

**Comment by krisgesling** [comment]
`afplay` on Mac, good to know.

Thanks for posting the solution for other users in the future
