### ISSUE TITLE
How is the data like to train my wake-word?

### ISSUE THREAD

**Issue by jaysimon** [MycroftAI/mycroft-precise#83]
I am trying to train my own wake word, I got a dataset of 1 million wake-word, 0.4 million not-wake-word. Test performance is good, while listen performance is not.
1. When you guys training ,what is the num of wake-word and not-wake-word?
2. How many epoch?
3. Any training tips?

**Comment by el-tocino** [comment]
Is that unique samples or are they copies of the same thing over and over?  Because that is a massive amount of samples.

Typically I got for 1:4 wake to not wake words.  Training depends on loss and accuracy, if it's getting better, I keep training.  Once you get to the high .999's in accuracy, find one you like (or use save best) and go with that.

**Comment by jaysimon** [comment]
@el-tocino 
Well, Data is unique samples, That's cost a lot.
1. Could you tell me the number of wake and not wake word you use?
2. According to the readme in precise, I notice that, data should end when wake word end.
I check my data, some data last about 0.5s after the word ended. Is that matter? 
3. Some data is shorter than 1.5s, so mfcc will be zeros in the first serval frames. Is that matter?

**Comment by el-tocino** [comment]
1. 500 wake, 100k not wake
2. I don't think that's a big deal.
3. see 2.

**Comment by jaysimon** [comment]
Vad is applied in the data, some data is not well split, there is some backgroud noise and half wake-word in the wake-word dataset

**Comment by jaysimon** [comment]
Thanks a lot!
I will report after try your advice!

**Comment by el-tocino** [comment]
The half wake word bits sound concerning, are they not the whole word? If so, then that's probably causing some issues....

**Comment by jaysimon** [comment]
Yes, some are not the whole word, but very litter.
I will check dataset carefully. Original data is about 20000, data argument with noise and nr, then got 1M.

**Comment by jaysimon** [comment]
@el-tocino
By the way, how many epoch have you trained?

**Comment by el-tocino** [comment]
Depends on the data, just a matter of watching the accuracy and loss.  Pull up tensorboard, watch the logs.  

Try dropping all but the original samples and modeling once, see how that turns out.

**Comment by jaysimon** [comment]
@el-tocino 
I trained a model with about 30000+ data, it's working fine. But it will wake when got some music noise, so, I tried to add more not-wake-word samples, then I cant wake it.
Any idea?
Pos:Neg = 131269:426886

**Comment by el-tocino** [comment]
add samples that contain the noises that are problematic to the not wake words, get samples of wakeword while the music's playing?

**Comment by jaysimon** [comment]
@el-tocino 
I made some data with music or babble (.etc) noise, then put them together to train. The result is not very good, I cant wake it. let me clarify the situtation:
1. Clean-wake-word(12159) + 10dB-NR-wake-word(381158) + not-wake-work(423554) +200 epoch = wake fine
2. Clean-wake-word(12159) + 10dB-NR-wake-word(381158) + (0dB, 5dB)NR-(different noise)-wake-word(750582) + not-wake-work(423554)  + 1000epoch = canot wake
Both of them works fine on test dataset, but diffient on precise-listen.
I wonder whether the one gru layer model is enougth to get a good generalization ability.
I will try more to find the reason.
Any idea?

**Comment by el-tocino** [comment]
I think you might want start with a base of your self-generated (ie, your voice, others who use its voices) samples and work from there.  Skip all the other samples.  Generate that model and see if it works.  

Alternatively, feel free to upload samples to https://github.com/MycroftAI/Precise-Community-Data and I might be able to try modeling off of them.

**Comment by jaysimon** [comment]
Thanks for your answer!

**Comment by jaysimon** [comment]
Thanks for your answer!
