### ISSUE TITLE
FYI - source install on ubuntu creates python dependency conflict

### ISSUE THREAD

**Issue by gcoon151** [MycroftAI/mycroft-precise#92]
Going to try and figure out how to make both hyperopt and bbopt happy with their versions of networkx but I installed this via source/setup.sh which grabbed the python dependencies on Ubuntu 18.04 and it created this odd conflict of dependency

ERROR: hyperopt 0.2.1 has requirement networkx==2.2, but you'll have networkx 2.4 which is incompatible.
ERROR: bbopt 1.1.6 has requirement networkx<2.0,>=1.0, but you'll have networkx 2.4 which is incompatible.

If I find a way to fix it for this, I'll submit a PR.

**Comment by gcoon151** [comment]
Dupe to this https://github.com/MycroftAI/mycroft-precise/issues/91

**Comment by MatthewScholefield** [comment]
Fixed via 2d65736.
