### ISSUE TITLE
Pyache usage problem

### ISSUE THREAD

**Issue by garymmi** [MycroftAI/mycroft-precise#96]
I trace the code precise/scripts/test.py and want to know how to get features
Then I trace into precise/train_data.py.
There is __load_files method to load wav and get mfcc.
i don't know what happen at this line
   cache = Pyache('.cache', lambda x: vectorizer(load_audio(x)), pr.vectorization_md5_hash())
i print some strings in load_audio() method, but when i run test.py , show nothing
it seem like no run load_audio()

Anyone know why?
Thanks

**Comment by MatthewScholefield** [comment]
[Pyache](https://github.com/MycroftAI/pyache/blob/master/README.md) is a caching library. Essentially, it assumes each audio filename will always have the same audio so it only loads it once, processes it, and saves the processed data in the .cache folder. If you want to force it to run, delete the ".cache" folder to force it to regenerate. Alternatively, you could add something to the hash to trigger it to reload once by writing something like `pr.vectorization_md5_hash() + 'something'`.

**Comment by garymmi** [comment]
I got it
Thanks for your reply.
