### ISSUE TITLE
ImportError: cannot import name 'create_parser'

### ISSUE THREAD

**Issue by sanderversteegh** [MycroftAI/mycroft-precise#98]
I’m traying to get mycroft-precise working. I first tray it on my RPI bud I got a error with a version conflict. So now I’m traying to get it to work on my ubuntu virtual machine. I followd the source install instructions  and after activating the virtual environment I first run ‘precise-collect’. Where I got the following error. 
```
Traceback (most recent call last):
  File "/home/sander/mycroft-precise-master/.venv/bin/precise-collect", line 11, in <module>
    load_entry_point('mycroft-precise', 'console_scripts', 'precise-collect')()
  File "/home/sander/mycroft-precise-master/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sander/mycroft-precise-master/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/sander/mycroft-precise-master/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/sander/mycroft-precise-master/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sander/mycroft-precise-master/precise/scripts/collect.py", line 21, in <module>
    from prettyparse import create_parser
ImportError: cannot import name 'create_parser'
```

What am I doing whrong?
Thank you for you’re help!

**Comment by MatthewScholefield** [comment]
There is a small issue with the master branch. To build the master branch properly you need to do the following:

```bash
source .venv/bin/activate
pip install 'prettyparse<1.0'
```

We should probably backport the change to the master branch

**Comment by sanderversteegh** [comment]
It look likes it works partley now. That error is gone.
Thank you vert mutch.

I have now a other problem. I had this problem also on the pi. While executing precise-collect I get a error saying I need hyperopt 0.1.2. 
`pkg_resources.DistributionNotFound: The 'hyperopt==0.1.2' distribution was not found and is required by mycroft-precise`
so I tell it to install that version of hyperopt.

Bud if I then run Mycroft-precise again I get the error that I need hyperopt 0.2.1 again.
`pkg_resources.ContextualVersionConflict: (hyperopt 0.1.2 (/home/sander/mycroft-precise/.venv/lib/python3.6/site-packages), Requirement.parse('hyperopt>=0.2.1; python_version >= "3"'), {'bbopt'})`
how can I solve this?

**Comment by MatthewScholefield** [comment]
Ah yes, the other error that needs to be backported. Try applying [the
following fix to your setup.py](
https://github.com/MycroftAI/mycroft-precise/commit/2d65736ba589af50297de46905799ac1b1485cf1)
and rerunning `./setup.sh`.

**Comment by sanderversteegh** [comment]
Whel, I got something working now!
It looks like the other error happens in de dev branch. I wend back to the master branch and trite you’re first solution and it works now. 
So I’m very happy now, thank you very much for you’re help!

**Comment by sanderversteegh** [comment]
I also trite your solution on the other error. When I edit setup.py to 
`        'networkx==2.2',
        'hyperopt==0.2.1'
    ]
)`

It dose it's setup without error's and starts precise-collect without problem.
I’m now gone play with it and find out how it works. 
Again, thank you.

**Comment by MatthewScholefield** [comment]
No problem. Just backported the commit (#101) so it shouldn't happen again.
